### ISSUE TITLE
有错误

### ISSUE THREAD

**Issue by valariz** [Python3WebSpider/CrackGeetest#1]
验证码位置 171 330 304 562
验证码位置 171 330 304 562
缺口位置 60
滑动轨迹 [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 2, 2, 2, 2]
Traceback (most recent call last):
  File "H:\crack.py", line 219, in <module>
    crack.crack()
  File "H:\crack.py", line 206, in crack
    EC.text_to_be_present_in_element((By.CLASS_NAME, 'geetest_success_radar_tip_content'), '验证成功'))
  File "C:\Python\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

python 3.6.2
pillow 4.2.1 
selenium 3.4.3
chromedriver 2.32
google chrome  61.0.3163.100

**Comment by iamGavinZhou** [comment]
我也试了下，发现captcha1和captcha2保存下来都是空白，只有出现代码所示的两张才能保存，而且无论验证成功与否最后都是time out，不知道为什么

**Comment by ben46** [comment]
有时候成功， 有时候失败， 不知道为啥

**Comment by ghost** [comment]
@valariz @iamGavinZhou @ben46         
`captcha = screenshot.crop((2*left, 2*top, 2*right, 2*bottom))`

**Comment by Kmyu1k** [comment]
@valariz @iamGavinZhou @ben46 
我这边测试到估计是高分屏的原因，截全图下来的时候我用画图软件看了图形验证码的像素位置，刚好是 @cong-long 给的位置参数乘以2，所以保存下来的2张验证码的图还要压缩一下分辨率，在下面加入2条语句就可以做对比匹配了。
`captcha = screenshot.crop((2*left, 2*top, 2*right, 2*bottom))`
```
size = 258,159
captcha.thumbnail(size)
```

**Comment by yikwing** [comment]
![image](https://user-images.githubusercontent.com/20245290/40226102-64d1ce62-5abd-11e8-9e2f-f280b6cd8cc6.png)

**Comment by yikwing** [comment]
macBook 高分屏截图全白   解决

![jietu20180518-170323](https://user-images.githubusercontent.com/20245290/40226124-7344cf8a-5abd-11e8-931f-a6487c9b67d1.jpg)

**Comment by goodbad3** [comment]
还是不行

**Comment by goodbad3** [comment]
Message: Failed to decode response from marionette
